### ISSUE TITLE
What is __client__ for in ipfsApi/client.py?

### ISSUE THREAD

**Issue by larsks** [ipfs/python-ipfs-api#11]
Why does `client.py` do this:

    class Client(object):

        __client__ = http.HTTPClient

And then:

    self._client = self.__client__(host, port, base, default_enc)
    
That's a lot of underscores, and `_client` and `__client__` are
perhaps too similar.  Why not simply:

    self._client = http.HTTPClient(host, port, base, default_enc)

? I'm not clear what the extra level of indirection is getting us.

**Comment by amstocker** [comment]
My intention was that at some point there could be an asynchronous HTTPClient, then in order to make a new ipfs api client you could just do:

.. code-block:: python

    class AsyncClient(Client):
        __client__ = AsyncHTTPClient

**Comment by larsks** [comment]
Makes sense.  Maybe it's just the naming of things that bothers me.  How about:

    class Client(object):
        clientfactory = http.HTTPClient

And then:

    def __init__(self, ...):
        self.client = self.clientfactory(host, port, base, default_enc)

**Comment by larsks** [comment]
^^^ like that, maybe.

**Comment by amstocker** [comment]
thanks, that does make a lot more sense
