### ISSUE TITLE
File Streaming

### ISSUE THREAD

**Issue by amstocker** [ipfs/python-ipfs-api#2]
I haven't been able to get file streaming for a recursive add working yet (right now I do multiple requests and manually set up the links).  I'm pretty sure requests itself can't render multi-part/mixed bodies, which is how the IPFS http api expects it; https://github.com/ipfs/go-ipfs/blob/master/docs/implement-api-bindings.md#note-on-multipart--inspecting-requests, so we might have to use urllib3 or just do it manually.  If anyone knows how to do this, some help would be greatly appreciated.

**Comment by amstocker** [comment]
Here is a good reference: https://github.com/djc/couchdb-python/blob/master/couchdb/multipart.py#L120

**Comment by BrendanBenshoof** [comment]
I avoided this problem a few months ago when I took a stab at this project becuase requests could not handle it trivially (I am hoping I will be doing useful PRs on this repo in a few days).

It might be worth forking + PRing requests with the feature rather than building just for this project.

https://github.com/kennethreitz/requests/issues/935

**Comment by amstocker** [comment]
Yeah we could definitely do that.  Looks like the multi-part encoding is done [here](https://github.com/kennethreitz/requests/blob/master/requests/models.py#L156) and [here](https://github.com/kennethreitz/requests/blob/master/requests/packages/urllib3/filepost.py#L58).

**Comment by jbenet** [comment]
Multipart is not super hard if you end up having to implement it. it sucks as a format.

(aside: I actually wanted to add support for other input formats: 

- tar stream
- length-prefixed multipart-like thing 

but we haven't yet. so i think multipart is still the best bet.)

**Comment by amstocker** [comment]
I got a multipart writer working today (see code [here](https://github.com/ipfs/python-ipfs-api/blob/master/ipfsApi/filestream.py)).  It also turns out that you can pass a generator to the [data] keyword arg in the requests api and it will read it as chunked input, so I would like to make a real multipart file streamer that just returns a generator that can be passes to requests.
