### ISSUE TITLE
get rid of CamelCase key names?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ipfs/python-ipfs-api#22]
Quite some key names in the data structures returned by the API are either camelcase or (if only one word) starting with an uppercase letter.

PEP8 mandates this_kind_of_names for function/method parameter names and there is some correspondance between them and dicts: if you use stuff like `**kwargs`, kwargs is a dict that has the parameter names as keys. If you explode a dict, key names from the dict get parameter names of functions and methods.

So, would it be a good idea to rename the key names to this_style? If desired, this change should be done early, before the api gets in wide usage.

**Comment by amstocker** [comment]
The reason they are in camelcase is because the responses you're getting are directly from the ipfs daemon (which is written in Go, hence the camelcase).

**Comment by ThomasWaldmann** [comment]
Ah, ok.

**Comment by amstocker** [comment]
Not that you're wrong, it would be nice, but I think it would probably be a pain to convert all the camelcase responses from the daemon to snake_case.  Eventually I would like to abstract over all the responses anyways.
