### ISSUE TITLE
get directory from hash

### ISSUE THREAD

**Issue by nmushegian** [ipfs/python-ipfs-api#28]
Is there a simple inverse operation for `hash = ipfs.add(directory_path, recrusive=True)[-1]["Hash"]`?

**Comment by amstocker** [comment]
Do you mean just getting an entire directory and saving it in to disk?  We currently don't support `ipfs get` but we definitely should soon (thanks for bringing this up!).  The result of `hash = ipfs.add(directory_path, recrusive=True)` is actually a list of all the individual files added to ipfs and their respective hashes, so the snippet you posted would result in an error.  In the mean time you will need to download and save each file by their individual hash.

**Comment by nmushegian** [comment]
Sorry, I meant `hash = ipfs.add(directory_path, recrusive=True)[-1]["Hash"]`; the hash the of the root directory.

**Comment by nmushegian** [comment]
Looking closer, it seems ipfs is similar to git in that directories are not objects. So there's no file layout metadata being added when I do `ipfs add -r ...` ?

**Comment by amstocker** [comment]
`ipfs add -r` will build the directory structure such that each directory has a hash, so the overall structure is certainly maintained.  If you took the result of `hash = ipfs.add(directory_path, recrusive=True)[-1]["Hash"]` and called `ipfs.ls(hash)` it would give you a list of all the files and subdirectories you in the folder you added and their respective hashes.  However, note that things like unix privileges are not currently retained.  Hope that helps!

**Comment by amstocker** [comment]
fixed by #30
